apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "sampleCiam.name" . }}
    helm.sh/chart: {{ include "sampleCiam.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-env-vars
data:
  {{- if .Values.pingOne.adminConsole.useMyPing }}
  ADMIN_CLIENT_ID: {{ .Values.pingOne.adminConsole.adminAppId | quote }}
  ADMIN_CLIENT_SECRET: {{ .Values.pingOne.adminConsole.adminAppSecret | quote }}
  ADMIN_CLIENT_ISSUER: {{ include "sampleCiam.pingOneAdminUrl" . | quote }}
  ADMIN_CLIENT_AUTHZ: "{{ include "sampleCiam.pingOneAdminUrl" . }}/authorize"
  ADMIN_CLIENT_TOKEN: "{{ include "sampleCiam.pingOneAdminUrl" . }}/token"
  ADMIN_CLIENT_USERINFO: "{{ include "sampleCiam.pingOneAdminUrl" . }}/userinfo"
  ADMIN_CLIENT_LOGOFF: "{{ include "sampleCiam.pingOneAdminUrl" . }}/signoff"
  PF_ADMIN_MODE: "OIDC"
  {{- else }}
  PF_ADMIN_MODE: "LDAP"
  PD_LDAP_SERVICE: "{{ .Release.Name }}-pingdirectory:{{ include "pingports.pdLdapPort" . }}"
  {{- end }}
  PING_IDENTITY_PASSWORD: {{ default "2FederateM0re" .Values.global.envs.PING_IDENTITY_PASSWORD | quote }}
  PF_ADMIN_PORT: {{ include "pingports.pfAdminPort" . | quote }}
  PF_ADMIN_HOSTNAME: {{ include "sampleCiam.pfAdminHostname" . | quote}}
  PF_ADMIN_TITLE: {{ .Release.Name }}
  PF_BASE_URL: {{ include "sampleCiam.hostname" .  | quote }}
  {{- if .Values.useCases.delegatedAdministration.enabled }}
  PD_DELEGATOR_PUBLIC_HOSTNAME: {{ include "sampleCiam.hostname" .  | quote }}
  PF_ENGINE_PUBLIC_HOSTNAME: {{ include "sampleCiam.hostname" .  | quote }}
  PF_ENGINE_PUBLIC_PORT: ""
  PF_DELEGATOR_CLIENTID: "Delegator"
  PD_ENGINE_PUBLIC_HOSTNAME: {{ include "sampleCiam.hostname" .  | quote }}
  PD_ENGINE_PUBLIC_PORT: "443"
  {{- end }}