{{- if not .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "sampleCiam.name" . }}
    helm.sh/chart: {{ include "sampleCiam.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: {{ .Release.Name }}-consoles-ingress
spec:
  # Use the AWS Route53 FQDNs to access the Admin Consoles
  rules:
  # This rule gives external access to the PingAccess Admin Console
  - host: pingaccess-{{ .Release.Name }}.ping-devops.com
    http:
      paths:
       - backend:
           serviceName: {{ .Release.Name }}-pingaccess
           servicePort: {{ include "pingports.paAdminPort" . }}
  # This rule gives external access to the PingFederate Admin Console
  - host: pingfederate-{{ .Release.Name }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingfederate-admin
          servicePort: {{ include "pingports.pfAdminPort" . }}
  # This rule gives external access to the PingData Admin Console
  - host: pingdataconsole-{{ .Release.Name }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingdataconsole
          servicePort: {{ include "pingports.pdConsolePort" . }}
  # This rule gives external access to the PingDirectory Config API
  - host: pingdirectory-{{ .Release.Name }}.ping-devops.com
    http:
      paths:
       - backend:
           serviceName: {{ .Release.Name }}-pingdirectory
           servicePort:  {{ include "pingports.pdConfigPort" . }}
  # This rule gives external access to the PingCentral Admin Console
  - host: pingcentral-{{ .Release.Name }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingcentral
          servicePort: {{ include "pingports.pcAdminPort" . }}
  tls:
    - hosts:
      - pingaccess-{{ .Release.Name }}.ping-devops.com
      - pingfederate-{{ .Release.Name }}.ping-devops.com
      - pingdataconsole-{{ .Release.Name }}.ping-devops.com
      - pingdirectory-{{ .Release.Name }}.ping-devops.com
      - pingcentral-{{ .Release.Name }}.ping-devops.com
{{- end -}}